name: catchit
description: "Drowsiness Detection Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # 카메라 및 AI 관련
  camera: ^0.11.0
  google_mlkit_face_detection: ^0.11.0
  
  # 권한 및 워치 연결
  watch_connectivity: ^0.2.8
  permission_handler: ^11.3.1
  
  # 알림 및 로컬 알림 패키지
  audioplayers: ^5.2.1
  vibration: ^2.0.1
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # assets 설정 (중복 제거 및 들여쓰기 교정)
  assets:  
    - assets/radar1.mp3
    - assets/깨록.png